version: '3'

services:
  caddy:
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - ./.config/Caddyfile.dev:/etc/Caddyfile

  vue:
    volumes:
      - ./pyShare-fe:/app
      - /app/node_modules/

  web:
    volumes:
      - ./pyShare-be:/app

  sandbox:
    volumes:
      - ./pyShare-sandbox:/app
